# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0e6e4b2609830200a2c2a4bb719a7f9183b243f4a29cbc732815df74c41a10d617e382c4057942abc62baa44f857c3ab0df60a1d4f947ce4212c437f4a701f6

test:
  secret_key_base: 9bf1f4b9b4d68e87d778ca4bfca3a4ad79b2e304f59cc90c3c18ffdb3d1d513073c88f96838676c7f1af4ff7e96dc99e3d92a3dc55690d02a4dd8d56d83bb84f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
